platform :'ios','9.0'
target 'HuaYiTianXia' do
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'YYModel'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
  use_frameworks!
end

